version: '2.1'
services:
  app:
    build: .
    volumes:
      - .:/var/www
    environment:
      - "REDIS_HOST=redis"
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_HOST=mysql"
      - "MYSQL_PORT=3306"
      - "MYSQL_DATABASE=octo"
      - "MYSQL_USER=octo"
      - "MYSQL_PASSWORD=octo"
      - "APPLICATION_ENV=development"
      - "APPLICATION_URL=http://www.rueduphp.com"
      - "SITE_NAME=rueduphp"
      - "MAILER_DRIVER=smtp"
      - "SMTP_HOST=mailtrap.io"
      - "SMTP_PORT=2525"
      - "SMTP_SECURITY=null"
      - "SMTP_USER=null"
      - "SMTP_PASSWORD=null"
      - "SENDMAIL_PATH=/usr/lib/sendmail"
    links:
      - mysql
      - redis

  mysql:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=octo"
      - "MYSQL_USER=octo"
      - "MYSQL_PASSWORD=octo"
    ports:
      - "3366:3306"

  redis:
    image: redis:4.0-alpine
    command: redis-server --appendonly yes
    ports:
      - "6377:6379"
