version: '2.1'
services:
  app:
    image: rueduphp/phpdevapp72
    volumes:
      - .:/var/www
    environment:
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "MYSQL_ROOT_PASSWORD=root"
      - "DATABASE_HOST=mysql"
      - "DATABASE_PORT=3306"
      - "DATABASE_NAME=octo"
      - "DATABASE_USER=octo"
      - "DATABASE_PASSWORD=octo"
      - "MYSQL_HOST=mysql"
      - "MYSQL_PORT=3306"
      - "MYSQL_DATABASE=octo"
      - "MYSQL_USER=octo"
      - "MYSQL_PASSWORD=octo"
      - "APPLICATION_ENV=development"
      - "APPLICATION_URL=http://www.rueduphp.com"
      - "SITE_NAME=rueduphp"
      - "MAILER_DRIVER=smtp"
      - "SMTP_HOST=maildev"
      - "SMTP_PORT=25"
      - "SMTP_SECURITY=null"
      - "SMTP_USER=null"
      - "SMTP_PASSWORD=null"
      - "SENDMAIL_PATH=/usr/lib/sendmail"
      - "CACHE_PATH=/var/www/data/cache"
      - "LOGS_PATH=/var/www/data/logs"
      - "TMP_PATH=/var/www/data/tmp"
      - "PUBLIC_PATH=/var/www/public"
      - "ASSETS_PATH=/var/www/public/assets"
      - "COMMANDS_PATH=/var/www/app/Commands"
    links:
      - mysql
      - postgres
      - redis
      - maildev

  mysql:
    image: mariadb
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=octo"
      - "MYSQL_USER=octo"
      - "MYSQL_PASSWORD=octo"
    ports:
      - "3366:3306"

  postgres:
    image: postgres:9.6
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=octo"
      - "POSTGRES_PASSWORD=octo"
      - "POSTGRES_DB=octo"
    ports:
      - "5532:5432"

  maildev:
    restart: always
    image: djfarrelly/maildev
    ports:
      - "1080:80"

  redis:
    image: redis:4.0-alpine
    command: redis-server --appendonly yes
    ports:
      - "6377:6379"
