#!/usr/bin/env php
<?php
    namespace Octo;

    use App\Bootstrap;

    require_once __DIR__ . '/vendor/autoload.php';

    call_user_func(function () {
        systemBoot(realpath(__DIR__ . '/app'));

        Octo::cli();

        (new Bootstrap())->cli(new Fast);

        $worker = new Work(new FastCache('jobs'));

        $computed = $worker->process();

        Cli::show($computed . ' jobs processed');
    });
